# -*- coding: utf-8 -*-
"""ann_scratch_Barep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hAB6t7gVEZ4Nwz1xSFcrU7ceazTrFVph
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from google.colab import files

# ========== 1. LOAD + PREPROCESS DATA ==========
print("Upload file Dry_Bean_Dataset.xlsx")
uploaded = files.upload()

df = pd.read_excel("Dry_Bean_Dataset.xlsx")

# Pisah X dan y
X = df.drop('Class', axis=1).values
y = df['Class'].values

# Label encode + One-hot encoding 7 kelas
le = LabelEncoder()
y = le.fit_transform(y)
y = np.eye(7)[y] # 7 neuron output

# Split 80:20 sesuai spek
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Normalisasi manual
mean = X_train.mean(axis=0)
std = X_train.std(axis=0)
X_train = (X_train - mean) / std
X_test = (X_test - mean) / std

print(f"Train: {X_train.shape}, Test: {X_test.shape}\n")

# ========== 2. FUNGSI AKTIVASI + LOSS ==========
def relu(z):
    return np.maximum(0, z)

def relu_deriv(z):
    return (z > 0).astype(float)

def softmax(z):
    exp_z = np.exp(z - np.max(z, axis=1, keepdims=True))
    return exp_z / exp_z.sum(axis=1, keepdims=True)

def mse_loss(y_pred, y_true):
    return np.mean((y_pred - y_true) ** 2)

# ========== 3. CLASS ANN FROM SCRATCH ==========
class ANN_From_Scratch:
    def __init__(self, input_size, hidden1, hidden2, output_size):
        # ZERO INITIALIZATION sesuai spek
        self.W1 = np.zeros((input_size, hidden1))
        self.b1 = np.zeros((1, hidden1))
        self.W2 = np.zeros((hidden1, hidden2))
        self.b2 = np.zeros((1, hidden2))
        self.W3 = np.zeros((hidden2, output_size))
        self.b3 = np.zeros((1, output_size))

    def forward(self, X):
        self.z1 = np.dot(X, self.W1) + self.b1
        self.a1 = relu(self.z1)

        self.z2 = np.dot(self.a1, self.W2) + self.b2
        self.a2 = relu(self.z2)

        self.z3 = np.dot(self.a2, self.W3) + self.b3
        self.a3 = softmax(self.z3) # output
        return self.a3

    def backward(self, X, y, lr):
        m = X.shape[0]

        # Output layer
        dz3 = self.a3 - y
        dW3 = np.dot(self.a2.T, dz3) / m
        db3 = np.sum(dz3, axis=0, keepdims=True) / m

        # Hidden layer 2
        da2 = np.dot(dz3, self.W3.T)
        dz2 = da2 * relu_deriv(self.z2)
        dW2 = np.dot(self.a1.T, dz2) / m
        db2 = np.sum(dz2, axis=0, keepdims=True) / m

        # Hidden layer 1
        da1 = np.dot(dz2, self.W2.T)
        dz1 = da1 * relu_deriv(self.z1)
        dW1 = np.dot(X.T, dz1) / m
        db1 = np.sum(dz1, axis=0, keepdims=True) / m

        # UPDATE BOBOT Mini-batch SGD sesuai spek lr=0.1
        self.W3 -= lr * dW3
        self.b3 -= lr * db3
        self.W2 -= lr * dW2
        self.b2 -= lr * db2
        self.W1 -= lr * dW1
        self.b1 -= lr * db1

    def train(self, X, y, epochs=50, batch_size=16, lr=0.1):
        for epoch in range(epochs):
            # Shuffle data tiap epoch
            idx = np.random.permutation(X.shape[0])
            X_shuffle, y_shuffle = X[idx], y[idx]

            # MINI-BATCH SGD sesuai spek batch_size=16
            for i in range(0, X.shape[0], batch_size):
                X_batch = X_shuffle[i:i+batch_size]
                y_batch = y_shuffle[i:i+batch_size]

                self.forward(X_batch)
                self.backward(X_batch, y_batch, lr)

            # Hitung loss tiap 10 epoch
            if epoch % 10 == 0:
                pred = self.forward(X)
                loss = mse_loss(pred, y)
                print(f"Epoch {epoch}: Loss = {loss:.4f}")

    def predict(self, X):
        pred = self.forward(X)
        return np.argmax(pred, axis=1)

# ========== 4. TRAINING ==========
input_size = X_train.shape[1] # 16
hidden1 = 64
hidden2 = 32
output_size = 7

model = ANN_From_Scratch(input_size, hidden1, hidden2, output_size)

print("Mulai Training...")
model.train(X_train, y_train, epochs=50, batch_size=16, lr=0.1)

# ========== 5. EVALUASI ==========
y_pred = model.predict(X_test)
y_true = np.argmax(y_test, axis=1)

accuracy = np.mean(y_pred == y_true) * 100
print(f"\nAkurasi Test: {accuracy:.2f}%")