# -*- coding: utf-8 -*-
"""Tugas_Besar_ANN_keras.NabilaRahayu(2303030015).ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n7cG6n4nMmPew227TKvrc4BUm5JqvCo9

# TUGAS BESAR KECERDASA BUATAN

## Implementasi Artificial Neural Network (ANN) Menggunakan TensorFlow Keras

**Nama Kelompok:** (Nabila Rahayu & Barep Purwo Agusto)

**Mata Kuliah:** Kecerdasan Buatan

**Dataset:** Dry Bean Dataset

**Framework:** TensorFlow Keras

**Optimizer:** SGD

**Learning Rate:** 0.1

**Epoch:** 50

**Batch Size:** 16

**Metode Inisialisasi Bobot yang Dibandingkan**

- Zero Initialization
- Xavier Initialization
- He Initialization
"""

import pandas as pd

import pandas as pd

df = pd.read_excel("Dry_Bean_Dataset.xlsx")

df.head()

df.shape

df.columns

df.info()

df.describe()

df["Class"].value_counts()

import pandas as pd

df = pd.read_excel("Dry_Bean_Dataset.xlsx")

df.head()

df.info()

X = df.iloc[:, :-1]

y = df.iloc[:, -1]

print(X.head())

print(y.head())

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

print(y[:10])

from tensorflow.keras.utils import to_categorical

y = to_categorical(y)

print(y[0])

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = scaler.fit_transform(X)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

model.add(Dense(
    units=32,
    activation='relu',
    input_shape=(16,)
))

model.add(Dense(
    units=7,
    activation='softmax'
))

model.summary()

def build_model(initializer):

    model = Sequential()

    model.add(Dense(
        units=32,
        activation='relu',
        input_shape=(16,),
        kernel_initializer=initializer
    ))

    model.add(Dense(
        units=7,
        activation='softmax',
        kernel_initializer=initializer
    ))

    return model

model = build_model("zeros")

model.summary()

from tensorflow.keras.optimizers import SGD

optimizer = SGD(
    learning_rate=0.1
)

from tensorflow.keras.optimizers import SGD

optimizer = SGD(
    learning_rate=0.1
)

model.compile(
    optimizer=optimizer,
    loss='mean_squared_error',
    metrics=['accuracy']
)

history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=16,
    validation_data=(X_test, y_test),
    verbose=1
)

import matplotlib.pyplot as plt

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.plot(history.history['accuracy'], label='Training Accuracy')

plt.plot(history.history['val_accuracy'], label='Validation Accuracy')

plt.title('Training dan Validation Accuracy')

plt.xlabel('Epoch')

plt.ylabel('Accuracy')

plt.legend()

plt.grid(True)

plt.show()

plt.figure(figsize=(8,5))

plt.plot(history.history['loss'], label='Training Loss')

plt.plot(history.history['val_loss'], label='Validation Loss')

plt.title('Training dan Validation Loss')

plt.xlabel('Epoch')

plt.ylabel('Loss')

plt.legend()

plt.grid(True)

plt.show()

plt.figure(figsize=(8,5))

plt.plot(history.history['loss'], label='Training Loss')

plt.plot(history.history['val_loss'], label='Validation Loss')

plt.title('Training dan Validation Loss')

plt.xlabel('Epoch')

plt.ylabel('Loss')

plt.legend()

plt.grid(True)

plt.show()

model = build_model("glorot_uniform")

from tensorflow.keras.optimizers import SGD

optimizer = SGD(
    learning_rate=0.1
)

model.compile(
    optimizer=optimizer,
    loss='mean_squared_error',
    metrics=['accuracy']
)

history_xavier = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=16,
    validation_data=(X_test, y_test),
    verbose=1
)

model = build_model("he_uniform")

from tensorflow.keras.optimizers import SGD

optimizer = SGD(
    learning_rate=0.1
)

model.compile(
    optimizer=optimizer,
    loss='mean_squared_error',
    metrics=['accuracy']
)

history_he = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=16,
    validation_data=(X_test, y_test),
    verbose=1
)

plt.figure(figsize=(8,5))

plt.plot(history_he.history['accuracy'], label='Training Accuracy')
plt.plot(history_he.history['val_accuracy'], label='Validation Accuracy')

plt.title('He Initialization - Accuracy')

plt.xlabel('Epoch')
plt.ylabel('Accuracy')

plt.legend()
plt.grid(True)

plt.show()

plt.figure(figsize=(8,5))

plt.plot(history_he.history['loss'], label='Training Loss')
plt.plot(history_he.history['val_loss'], label='Validation Loss')

plt.title('He Initialization - Loss')

plt.xlabel('Epoch')
plt.ylabel('Loss')

plt.legend()
plt.grid(True)

plt.show()

print("Train Accuracy :", history_he.history['accuracy'][-1])
print("Validation Accuracy :", history_he.history['val_accuracy'][-1])

print("Train Loss :", history_he.history['loss'][-1])
print("Validation Loss :", history_he.history['val_loss'][-1])

y_pred = model.predict(X_test)

import numpy as np

y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred_classes))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred_classes)

print(cm)

y_pred = model.predict(X_test)

import numpy as np

y_pred_classes = np.argmax(y_pred, axis=1)

y_true = np.argmax(y_test, axis=1)

from sklearn.metrics import classification_report

print(classification_report(
    y_true,
    y_pred_classes
))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_true,
    y_pred_classes
)

print(cm)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

plt.imshow(cm)

plt.colorbar()

plt.title("Confusion Matrix")

plt.xlabel("Predicted Label")

plt.ylabel("True Label")

plt.show()

import pandas as pd

hasil = pd.DataFrame({

    "Metode": [
        "Zero Initialization",
        "Xavier Initialization",
        "He Initialization"
    ],

    "Train Accuracy": [
        history.history['accuracy'][-1],
        history_xavier.history['accuracy'][-1],
        history_he.history['accuracy'][-1]
    ],

    "Validation Accuracy": [
        history.history['val_accuracy'][-1],
        history_xavier.history['val_accuracy'][-1],
        history_he.history['val_accuracy'][-1]
    ],

    "Train Loss": [
        history.history['loss'][-1],
        history_xavier.history['loss'][-1],
        history_he.history['loss'][-1]
    ],

    "Validation Loss": [
        history.history['val_loss'][-1],
        history_xavier.history['val_loss'][-1],
        history_he.history['val_loss'][-1]
    ]

})

hasil

terbaik = hasil.sort_values(
    by="Validation Accuracy",
    ascending=False
)

terbaik

plt.figure(figsize=(8,5))

plt.bar(
    hasil["Metode"],
    hasil["Validation Accuracy"]
)

plt.title("Perbandingan Validation Accuracy")

plt.ylabel("Accuracy")

plt.show()

best = hasil.loc[
    hasil["Validation Accuracy"].idxmax()
]

print(best)

hasil.to_excel(
    "Hasil_Perbandingan_ANN.xlsx",
    index=False
)

print("File berhasil disimpan.")

model.save("Model_ANN_He.keras")